### PR TITLE
check the by-id path for a USB stick

### PR DESCRIPTION
**Pull request by linux-universe**
would solve the **:** problem since the unix path does not contain **:**

_not 100% sure if the code is correct_

### CODE REVIEW

**Comment by linux-universe** [comment]
the recognition of the :0 does work but not the fallback to the unix path

Help appreciated

**Comment by happymab** [comment]
This worked in my tests:
TIK_INSTALL_DEVICE="$(readlink -f "/dev/disk/"${disk_id}"/"${result}"")"

note that it's slightly different than what I posted in the Matrix chat. It uses the ${disk_id} variable that is available.

I think this will work for the USB-disk-ids case only, not for the fallback that is in the previous code. Therefore you should probably use a separate if check for the USB case.

**Comment by linux-universe** [comment]
Thanks!

**Comment by happymab** [comment]
Hmm, I thought your if check should be separate, outside the other fallback if clause. Didn't think it through though and didn't test myself.

**Comment by linux-universe** [comment]
code unnecessary

**Pull request closed without merging**
